zuul:
  routes:
    producer:
      serviceId: kmr-hello-client
spring:
  application:
    name: kmr-zuul-loadbalancer
eureka:
  client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost